In [1]:
import numpy as np

In [2]:
np.random.random(1)

array([0.22156122])

In [3]:
np.random.random(2)

array([0.14818746, 0.51115606])

In [4]:
np.random.random((2,2))

array([[0.88425292, 0.52958291],
       [0.23345272, 0.14293433]])

In [9]:
np.random.randint(1, 10)

6

In [8]:
np.random.randint(1, 10, (2,2))         # generating random integers in a 2-d matrices

array([[8, 9],
       [1, 4]])

In [10]:
np.random.randint(1, 10, (3,4,5))       # generating random integers in a 3-d matrices

array([[[3, 6, 2, 8, 2],
        [5, 6, 5, 8, 6],
        [2, 3, 5, 6, 8],
        [8, 8, 9, 8, 1]],

       [[5, 2, 2, 8, 4],
        [7, 2, 6, 8, 2],
        [1, 5, 2, 3, 4],
        [4, 1, 9, 6, 5]],

       [[4, 1, 6, 3, 5],
        [1, 8, 4, 5, 4],
        [8, 5, 2, 3, 9],
        [7, 5, 6, 9, 1]]])

In [12]:
np.random.rand(2,2)

array([[0.78010284, 0.35144997],
       [0.77416425, 0.12849253]])

In [13]:
np.random.randn(2,2)            # generate +ve and -ve random values as well using randn

array([[ 1.59073112,  0.07710946],
       [-0.19994798,  0.03149725]])

In [14]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [15]:
np.random.choice(a)         # chosing some random values from a given array 

3